### ISSUE TITLE
finding com ports

### ISSUE THREAD

**Issue by fanoush** [dgofman/rp_BOOTSEL-#1]
Hi, nice script. However it has no chance of working on my PC since I used so many different boards a new one gets COM56 or something like that. Better is to use e.g. WMI to query com ports and manufacturer and maybe even USB VID/PID and find it that way.

You may try to run
```
WMIC.exe path  win32_pnpentity where "PNPClass='Ports'" get  Caption,Name,Manufacturer,status,PNPDeviceID
```
to get the idea. Maybe there is python WMI library on windows?

And BTW there is Pico 2 with drive name "RP2350"

**Comment by dgofman** [comment]
Hi @fanoush,

Thank you for your feedback! I wanted to clarify a few points based on your observations:

Partition Name:
Please take a look at the README file for details. If you're using a different partition name, update the following line accordingly:

```
partitionName = "RP2350"  # Replace with your partition name
```

COM Port Configuration:
I use the Arduino IDE (for C++ code) and Thonny (for MicroPython) on my setup. These tools handle code uploads to my RP2040 device, typically on COM8 and COM9. When compiling my C code using CMake, Windows assigns COM7.

To reduce the number of ports being scanned, I’ve configured the range as documented:

```
Copy code
initComPort = 7   # Starting COM port for device detection
maxComPorts = 9   # Ending COM port for device detection
```
This approach minimizes unnecessary scanning and speeds up the process.

**Comment by dgofman** [comment]
@fanoush,
Thank you for bringing the WMIC.exe utility to my attention! I've added a new feature to the script that automatically scans for registered COM ports on the computer.

**Comment by dgofman** [comment]
@fanoush,

Please let me know if I can close this issue or if you have any additional suggestions. I’d also greatly appreciate it if you could give the project a star! This simple utility helps prevent USB connection issues on your computer and protects your Raspberry Pi from potential damage.

**Comment by fanoush** [comment]
>  Thank you for bringing the WMIC.exe utility to my attention! I've added a new feature to the script that automatically scans for registered COM ports on the computer.

What I meant with this is that you could use wmic.exe as part of your script (if there is no WMI python library to import) to determine the port by some Pico specific value in name or vid/pid so your script would not need to scan/open wrong ports at all. And the script could also possibly have an option to list the ports with the name so user could see and pick the port manually from the name, again without the script attempting to open random other ports.

> Please let me know if I can close this issue or if you have any additional suggestions.

Yes, definitely close it as you wish, these are just tips to consider, no need to add them if you don't feel so.

**Comment by dgofman** [comment]
@fanoush 
Please pull the latest changes. I’ve added logic to automatically detect the registered COM port on your computer, eliminating the need to scan all ports. For backward compatibility, I’ve also kept the manual scan option, which can be used in cases where the COM port isn’t correctly registered in Windows RegEdit.

**Comment by fanoush** [comment]
> I’ve added logic to automatically detect the registered COM port on your computer, eliminating the need to scan all ports.

thanks, you mean this commit https://github.com/dgofman/rp_BOOTSEL-/commit/629ff61bc25a5985dca3170a1eba50a2e44fa587 or is there something newer that you forgot to push to the repo? I don't see anything newer.

If it is the latest one then yes I've seen that before writing previous comment, however after that commit it still scans all ports as seen in registry so if there is another device on another COM port it may pick the wrong one.  So I am not sure what do you mean by "eliminating the need to scan all ports" - it still scans all available ports.

**Comment by dgofman** [comment]
@fanoush 
Apologies, due to a conflict, my latest changes were not merged. I have resubmitted them.
